# docker-compose.yml
version: '2.2'

services:
    db:
        image: mysql:5
        ports:
            - 3310:3306 # port externe : port interne
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: eterelz
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        #volumes: 
        #    - ./docker/mysql/.:/var/lib/mysql #Possibilité d'avoir une base de données persistant hors container
    php:
        build:
            context: ../
            dockerfile: ./Docker_API/docker/Dockerfile
        volumes:
            - /code/vendor #Refuse le dossier vendor
            - ../:/code:cached #Prend tout les fichier de SmartLiving
    nginx:
        image: nginx:stable-alpine
        volumes_from:
            - php
        volumes:
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        links:
            - php

